// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discount.proto

package discountpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=productName,proto3" json:"productName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountRequest) Reset() {
	*x = GetDiscountRequest{}
	mi := &file_discount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountRequest) ProtoMessage() {}

func (x *GetDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountRequest.ProtoReflect.Descriptor instead.
func (*GetDiscountRequest) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiscountRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type CouponModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	Desciption    string                 `protobuf:"bytes,3,opt,name=desciption,proto3" json:"desciption,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponModel) Reset() {
	*x = CouponModel{}
	mi := &file_discount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponModel) ProtoMessage() {}

func (x *CouponModel) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponModel.ProtoReflect.Descriptor instead.
func (*CouponModel) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{1}
}

func (x *CouponModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponModel) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CouponModel) GetDesciption() string {
	if x != nil {
		return x.Desciption
	}
	return ""
}

func (x *CouponModel) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *CouponModel           `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiscountRequest) Reset() {
	*x = CreateDiscountRequest{}
	mi := &file_discount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiscountRequest) ProtoMessage() {}

func (x *CreateDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiscountRequest.ProtoReflect.Descriptor instead.
func (*CreateDiscountRequest) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDiscountRequest) GetCoupon() *CouponModel {
	if x != nil {
		return x.Coupon
	}
	return nil
}

type UpdateDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *CouponModel           `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiscountRequest) Reset() {
	*x = UpdateDiscountRequest{}
	mi := &file_discount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiscountRequest) ProtoMessage() {}

func (x *UpdateDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiscountRequest.ProtoReflect.Descriptor instead.
func (*UpdateDiscountRequest) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDiscountRequest) GetCoupon() *CouponModel {
	if x != nil {
		return x.Coupon
	}
	return nil
}

type DeleteDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=productName,proto3" json:"productName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiscountRequest) Reset() {
	*x = DeleteDiscountRequest{}
	mi := &file_discount_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiscountRequest) ProtoMessage() {}

func (x *DeleteDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiscountRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiscountRequest) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDiscountRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type DeleteDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiscountResponse) Reset() {
	*x = DeleteDiscountResponse{}
	mi := &file_discount_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiscountResponse) ProtoMessage() {}

func (x *DeleteDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discount_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiscountResponse.ProtoReflect.Descriptor instead.
func (*DeleteDiscountResponse) Descriptor() ([]byte, []int) {
	return file_discount_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDiscountResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_discount_proto protoreflect.FileDescriptor

const file_discount_proto_rawDesc = "" +
	"\n" +
	"\x0ediscount.proto\x12\bdiscount\x1a\x1cgoogle/api/annotations.proto\"6\n" +
	"\x12GetDiscountRequest\x12 \n" +
	"\vproductName\x18\x01 \x01(\tR\vproductName\"w\n" +
	"\vCouponModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vproductName\x18\x02 \x01(\tR\vproductName\x12\x1e\n" +
	"\n" +
	"desciption\x18\x03 \x01(\tR\n" +
	"desciption\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\"F\n" +
	"\x15CreateDiscountRequest\x12-\n" +
	"\x06coupon\x18\x01 \x01(\v2\x15.discount.CouponModelR\x06coupon\"F\n" +
	"\x15UpdateDiscountRequest\x12-\n" +
	"\x06coupon\x18\x01 \x01(\v2\x15.discount.CouponModelR\x06coupon\"9\n" +
	"\x15DeleteDiscountRequest\x12 \n" +
	"\vproductName\x18\x01 \x01(\tR\vproductName\"2\n" +
	"\x16DeleteDiscountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess2\xcb\x03\n" +
	"\x14DiscountProtoService\x12g\n" +
	"\vGetDiscount\x12\x1c.discount.GetDiscountRequest\x1a\x15.discount.CouponModel\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/discount/{productName}\x12g\n" +
	"\x0eCreateDiscount\x12\x1f.discount.CreateDiscountRequest\x1a\x15.discount.CouponModel\"\x1d\x82\xd3\xe4\x93\x02\x17:\x06coupon\"\r/api/discount\x12g\n" +
	"\x0eUpdateDiscount\x12\x1f.discount.UpdateDiscountRequest\x1a\x15.discount.CouponModel\"\x1d\x82\xd3\xe4\x93\x02\x17:\x06coupon\x1a\r/api/discount\x12x\n" +
	"\x0eDeleteDiscount\x12\x1f.discount.DeleteDiscountRequest\x1a .discount.DeleteDiscountResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/discount/{productName}BsZagithub.com/mustafaakcakaya/golang-microservices-ecommerce/internal/discount/discountpb;discountpb\xaa\x02\rDiscount.Grpcb\x06proto3"

var (
	file_discount_proto_rawDescOnce sync.Once
	file_discount_proto_rawDescData []byte
)

func file_discount_proto_rawDescGZIP() []byte {
	file_discount_proto_rawDescOnce.Do(func() {
		file_discount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discount_proto_rawDesc), len(file_discount_proto_rawDesc)))
	})
	return file_discount_proto_rawDescData
}

var file_discount_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_discount_proto_goTypes = []any{
	(*GetDiscountRequest)(nil),     // 0: discount.GetDiscountRequest
	(*CouponModel)(nil),            // 1: discount.CouponModel
	(*CreateDiscountRequest)(nil),  // 2: discount.CreateDiscountRequest
	(*UpdateDiscountRequest)(nil),  // 3: discount.UpdateDiscountRequest
	(*DeleteDiscountRequest)(nil),  // 4: discount.DeleteDiscountRequest
	(*DeleteDiscountResponse)(nil), // 5: discount.DeleteDiscountResponse
}
var file_discount_proto_depIdxs = []int32{
	1, // 0: discount.CreateDiscountRequest.coupon:type_name -> discount.CouponModel
	1, // 1: discount.UpdateDiscountRequest.coupon:type_name -> discount.CouponModel
	0, // 2: discount.DiscountProtoService.GetDiscount:input_type -> discount.GetDiscountRequest
	2, // 3: discount.DiscountProtoService.CreateDiscount:input_type -> discount.CreateDiscountRequest
	3, // 4: discount.DiscountProtoService.UpdateDiscount:input_type -> discount.UpdateDiscountRequest
	4, // 5: discount.DiscountProtoService.DeleteDiscount:input_type -> discount.DeleteDiscountRequest
	1, // 6: discount.DiscountProtoService.GetDiscount:output_type -> discount.CouponModel
	1, // 7: discount.DiscountProtoService.CreateDiscount:output_type -> discount.CouponModel
	1, // 8: discount.DiscountProtoService.UpdateDiscount:output_type -> discount.CouponModel
	5, // 9: discount.DiscountProtoService.DeleteDiscount:output_type -> discount.DeleteDiscountResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_discount_proto_init() }
func file_discount_proto_init() {
	if File_discount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discount_proto_rawDesc), len(file_discount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discount_proto_goTypes,
		DependencyIndexes: file_discount_proto_depIdxs,
		MessageInfos:      file_discount_proto_msgTypes,
	}.Build()
	File_discount_proto = out.File
	file_discount_proto_goTypes = nil
	file_discount_proto_depIdxs = nil
}
